# This is a basic workflow to help you get started with Actions
name: Build html
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build the html.
        run: python generateHtml.py
        
      - uses: actions/upload-artifact@v2
        with:
          name: index
          path: ./index.html
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: index
          path: index.html
