name: Build and Deploy HTML
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
      name: Build
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Build HTML
        run: python generateHtml.py
      - name: Save Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: html-dir
          path: output
#  deploy:
#    name: Deploy
#    runs-on: ubuntu-latest
#    needs: deploy